name: conda-vendor-dependencies
channels:
  - conda-forge
dependencies:
  - python
  - click
  - conda-lock>=1.2.*
  - conda-build  
  - pip
  # solvers
  - conda
  - mamba
  - micromamba
  # teset dependencies
  - pytest
  - pytest-mock
  - setuptools
  - wheel
   






